//! Parity test: re-runs ONNX inference on every row of `tests/parity_fixture.csv`
//! and asserts each prob_l1 / prob_l2 matches the Python reference within 1e-4.
//!
//! The fixture is generated by `scripts/export_onnx.py all`, which runs the
//! same ONNX models via onnxruntime-python and records the expected probs.
//! That makes this a Python-ONNX vs Rust-ONNX parity check (not Rust vs the
//! original sklearn pipeline). Tighter tolerance, simpler invariant.

use std::collections::HashMap;
use std::path::PathBuf;

use serde::Deserialize;

use gnss_defense_edge::inference::dual_runner::DualRunner;
use gnss_defense_edge::inference::feature_slice::{
    aissou_feature_order, slice_aissou, slice_texbat, TEXBAT_FEATURE_ORDER,
};

#[derive(Debug, Deserialize)]
struct FixtureRow {
    scenario: String,
    tick: u64,
    is_attack: u8,
    prob_l1: f32,
    prob_l2: f32,
    ratio_l1: f32,
    ratio_l2: f32,
    verdict: String,
    #[serde(flatten)]
    features: HashMap<String, f64>,
}

#[test]
fn rust_onnx_matches_python_onnx() -> anyhow::Result<()> {
    let crate_dir: PathBuf = env!("CARGO_MANIFEST_DIR").into();
    let assets_dir = crate_dir.join("assets");
    let fixture = crate_dir.join("tests/parity_fixture.csv");

    let mut rdr = csv::ReaderBuilder::new()
        .has_headers(true)
        .from_path(&fixture)?;
    let rows: Vec<FixtureRow> = rdr.deserialize().collect::<Result<_, _>>()?;
    assert!(!rows.is_empty(), "parity fixture is empty");

    let mut runner = DualRunner::load(&assets_dir)?;
    let (t_l1, t_l2) = runner.thresholds();

    let mut max_l1_diff = 0f32;
    let mut max_l2_diff = 0f32;
    let mut verdict_mismatches = 0usize;

    for (i, row) in rows.iter().enumerate() {
        // Sanity: every fixture row carries every feature.
        for &k in &TEXBAT_FEATURE_ORDER {
            assert!(
                row.features.contains_key(k),
                "row {i} ({}) missing TEXBAT feature {k}",
                row.scenario
            );
        }
        for k in aissou_feature_order() {
            assert!(
                row.features.contains_key(&k),
                "row {i} ({}) missing AISSOU feature {k}",
                row.scenario
            );
        }

        let l1 = slice_texbat(&row.features)?;
        let l2 = slice_aissou(&row.features)?;
        let (p_l1, p_l2, _us) = runner.run(&l1, &l2)?;

        let d1 = (p_l1 - row.prob_l1).abs();
        let d2 = (p_l2 - row.prob_l2).abs();
        max_l1_diff = max_l1_diff.max(d1);
        max_l2_diff = max_l2_diff.max(d2);
        assert!(
            d1 < 1e-4,
            "row {i} ({} tick={}): prob_l1 diff {d1:.2e} > 1e-4 (rust={p_l1} py={})",
            row.scenario,
            row.tick,
            row.prob_l1
        );
        assert!(
            d2 < 1e-4,
            "row {i} ({} tick={}): prob_l2 diff {d2:.2e} > 1e-4 (rust={p_l2} py={})",
            row.scenario,
            row.tick,
            row.prob_l2
        );

        // Cross-check ratios + verdict using the same thresholds.
        let r_l1 = if t_l1 > 0.0 { p_l1 / t_l1 } else { 0.0 };
        let r_l2 = if t_l2 > 0.0 { p_l2 / t_l2 } else { 0.0 };
        let max_r = r_l1.max(r_l2);
        let rust_verdict = if max_r >= 1.5 {
            "CRITICAL"
        } else if max_r >= 1.0 {
            "WARNING"
        } else {
            "OK"
        };
        if rust_verdict != row.verdict {
            verdict_mismatches += 1;
            eprintln!(
                "verdict mismatch row {i} ({} tick={}): rust={rust_verdict} py={} (r1={r_l1:.4} r2={r_l2:.4})",
                row.scenario, row.tick, row.verdict
            );
        }
        // is_attack is just for reference, not asserted (model accuracy is not
        // what this test measures — parity is).
        let _ = row.ratio_l1;
        let _ = row.ratio_l2;
        let _ = row.is_attack;
    }

    eprintln!(
        "parity OK on {} rows; max diffs: l1={:.2e} l2={:.2e}; verdict mismatches={}",
        rows.len(),
        max_l1_diff,
        max_l2_diff,
        verdict_mismatches
    );
    assert_eq!(
        verdict_mismatches, 0,
        "verdicts must match given identical probs and thresholds"
    );
    Ok(())
}
